<?php namespace App;

/**
 * Eloquent class to describe the property_type_values table
 *
 * automatically generated by ModelGenerator.php
 */
class PropertyTypeValues extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'property_type_values';

    public $timestamps = false;

    protected $fillable = array('order', 'value');

    public function propertyTypes()
    {
        return $this->belongsTo('App\PropertyTypes', 'property_type_id', 'id');
    }

    public function propertyTypeValueTranslations()
    {
        return $this->hasMany('App\PropertyTypeValueTranslations', 'property_type_value_id', 'id');
    }

    public function studentPropertyValues()
    {
        return $this->hasMany('App\StudentPropertyValues', 'property_type_value_id', 'id');
    }
}
