<?php namespace App;

/**
 * Eloquent class to describe the property_type_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class PropertyTypeTranslations extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'property_type_translations';

    public $timestamps = false;

    protected $fillable = array('locale', 'name', 'description');

    public function propertyTypes()
    {
        return $this->belongsTo('App\PropertyTypes', 'property_type_id', 'id');
    }
}
