<?php namespace App;

/**
 * Eloquent class to describe the property_type_value_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class PropertyTypeValueTranslations extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'property_type_value_translations';

    public $timestamps = false;

    protected $fillable = array('locale', 'name');

    public function propertyTypeValues()
    {
        return $this->belongsTo('App\PropertyTypeValues', 'property_type_value_id', 'id');
    }
}
