<?php namespace App;

/**
 * Eloquent class to describe the student_property_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentPropertyTranslations extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_property_translations';

    public $timestamps = false;

    protected $fillable = array('locale', 'name', 'description');

    public function studentProperties()
    {
        return $this->belongsTo('App\StudentProperties', 'student_property_id', 'id');
    }
}
