<?php namespace App;

/**
 * Eloquent class to describe the students table
 *
 * automatically generated by ModelGenerator.php
 */
class Students extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'students';

    public $timestamps = false;

    public function getDates()
    {
        return array('graduation_year');
    }

    protected $fillable = array('graduation_year', 'student_number', 'school_id');

    public function studentPropertyValues()
    {
        return $this->hasMany('App\StudentPropertyValues', 'student_id', 'id');
    }
}
