<?php namespace App;

/**
 * Eloquent class to describe the student_properties table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentProperties extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_properties';

    public $timestamps = false;

    protected $fillable = array('order', 'allow_multiple');

    public function propertyTypes()
    {
        return $this->belongsTo('App\PropertyTypes', 'property_type_id', 'id');
    }

    public function studentProperties()
    {
        return $this->belongsTo('App\StudentProperties', 'parent_student_property_id', 'id');
    }

    public function studentFormProperties()
    {
        return $this->hasMany('App\StudentFormProperties', 'student_properties_id', 'id');
    }

    public function studentProperties()
    {
        return $this->hasMany('App\StudentProperties', 'parent_student_property_id', 'id');
    }

    public function studentPropertyTranslations()
    {
        return $this->hasMany('App\StudentPropertyTranslations', 'student_property_id', 'id');
    }

    public function studentPropertyValues()
    {
        return $this->hasMany('App\StudentPropertyValues', 'student_property_id', 'id');
    }
}
