<?php namespace App;

/**
 * Eloquent class to describe the student_form_properties table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentFormProperties extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_form_properties';

    public $timestamps = false;

    public $incrementing = false;

    protected $fillable = array('order');

    public function studentFormSections()
    {
        return $this->belongsTo('App\StudentFormSections', 'student_form_section_id', 'id');
    }

    public function studentProperties()
    {
        return $this->belongsTo('App\StudentProperties', 'student_properties_id', 'id');
    }
}
