<?php namespace App;

/**
 * Eloquent class to describe the student_property_values table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentPropertyValues extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_property_values';

    public $timestamps = false;

    protected $fillable = array('order', 'propery_value');

    public function propertyTypeValues()
    {
        return $this->belongsTo('App\PropertyTypeValues', 'property_type_value_id', 'id');
    }

    public function studentProperties()
    {
        return $this->belongsTo('App\StudentProperties', 'student_property_id', 'id');
    }

    public function students()
    {
        return $this->belongsTo('App\Students', 'student_id', 'id');
    }

    public function studentPropertyValueTranslations()
    {
        return $this->hasMany('App\StudentPropertyValueTranslations', 'student_property_values_id', 'id');
    }
}
