<?php namespace App;

/**
 * Eloquent class to describe the student_property_value_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentPropertyValueTranslations extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_property_value_translations';

    public $timestamps = false;

    protected $fillable = array('locale', 'name', 'description');

    public function studentPropertyValues()
    {
        return $this->belongsTo('App\StudentPropertyValues', 'student_property_values_id', 'id');
    }
}
