<?php namespace App;

/**
 * Eloquent class to describe the student_form_section_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class StudentFormSectionTranslations extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'student_form_section_translations';

    public $timestamps = false;

    protected $fillable = array('locale', 'name', 'description');

    public function studentFormSections()
    {
        return $this->belongsTo('App\StudentFormSections', 'student_form_section_id', 'id');
    }
}
